# Generated by Django 6.0 on 2026-09-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0013_alter_quiz_close_time_alter_quiz_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='activity_mode',
            field=models.CharField(blank=True, default='INDIVIDUAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='group_revision',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
