# Generated by Django 6.0 on 2026-09-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0014_student_birthdate_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Time spent in seconds'),
        ),
    ]
