# Generated by Django 4.2.27 on 2026-09-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0015_quizattempt_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='grade_type',
            field=models.CharField(choices=[('WRITTEN_WORK', 'Written Work'), ('PERFORMANCE_TASK', 'Performance Task'), ('FINAL_EXAM', 'Final Exam')], db_index=True, default='WRITTEN_WORK', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded')], db_index=True, default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.CharField(choices=[('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8'), ('GRADE_9', 'Grade 9'), ('GRADE_10', 'Grade 10')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=10),
        ),
        migrations.AddIndex(
            model_name='quarterlygrade',
            index=models.Index(fields=['SubjectOffering', 'semester'], name='idx_qg_offering_sem'),
        ),
        migrations.AddIndex(
            model_name='quarterlygrade',
            index=models.Index(fields=['student', 'semester'], name='idx_qg_student_sem'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['SubjectOffering', 'status'], name='idx_quiz_offering_status'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'status'], name='idx_attempt_quiz_status'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'student'], name='idx_attempt_quiz_student'),
        ),
    ]
